label prologue:
    "After hour of searching I had finally found a college building!"
    me "It’s not so easy to find anything in this city!"
    "I exclaimed getting tired of the route. I had-to walk about two kilometers, because buses don’t drive to this district."
    th "Why did my parents choose this one? \"Well? Son, you’d rather to enroll there, at least you will be a respected man, this is a prestigious college!\""
    "Honestly, a prestige of education would have been senseless, if my second aunt hadn’t lived here and had agreed to give houseroom to me. Actually, I am from Russia and I don’t want to live in student hostel."
    "Also in this college studies my second cousin Mickey. Actually, we weren’t so close friends, but ones she had visited us and made a good impression of herself."
    "Actually, She isn’t a blood relative to me, so she was born before my sister’s marriage. She is my second step-cousin."
    "..."
    "So, I stood at the gates to Pedagogical College. I opened the door and went to the dean’s office."
    "Nobody was inside. Nobody sat at the desks, there was no query, there was no even a note: \"lunch break\"."
    th "Seems like I relaxed to early. It is not enough to find a college, I need to to find a people there."
    "I had-to decide something and I had decided to..."
    menu:
        "Wait":
            "I sat on the chair, awaiting, that someone will come."
            th "I really don’t like this idea!"
            th "Moving so many kilometers to get such a great reception."
            th "Good plan, ma and da."
            th "Is it really prestige college, or everyone is met such a way? Is it something like a test?"
            th "Super-elite college."
            "Suddenly my thread of hate was interrupted by some strange noise from the one of the desks."
            "I got up to check."
            "Under the desk set some ugly creature and did something with it hands. It was enjoying his occupation."
            "I remembered a book, that I used to love to read during my childhood. This name was \"Evenings on a Farm Near Dikanka \"."
            "In front of me me stood a real imp, similar to the one, which was painted in the book."
            "A beast noticed my presence, screamed loudly and jumped off me."
            menu:
                "Make a cross of pencils.":
                    "According to information from the book, I grabbed two pencils from dice-dox, that was on the desk, and formed a cross with them."
                    "The imp screamed louder, twitched and ran around the office."
                    "I started to pursue him, speaking:"
                    me "Get out, you devilry!"
                    "Understanding, that I won’t let him go, the imp jumped through the window, breaking a glass."
                    th "I understand nothing."  
                    " The door squeaked, and I turned around,preparing my weapon."
                    me "Get lost, you, server of Satan, I gonna hit you by the cross!"
                    mky "Don’t beat me please!"
                    "I heard a well known voice."
                    "It was Mickey, grown up from the last time we had met."
                    me "Mickey! Thanks God! At least you explain me what’s going on?"
                    mky "Actually, I really don’t understand..."
                    me "Well. Who is studying here: you or me?"
                    mky "It seems like a devils broke out the basement and made here a mess."
                    me "The devils? In the basement? It isn’t a college, it is devil knows what."
                    mky "I don’t know, how did it happened. We are hiding in psychologist’s office and we don’t know what to do."
                    me "Well, lead me there then we will come up with something."
                    $ add_event('Встретил Микки и прогнал беса')
                    #$ meet_micky_and_imp_removed = True
                    jump physchologists_office
                "To do nothing":
                    "I stood affected, wasn’t knowing what to do."
                    "Taking advantage of my idleness the imp punched me with a hoof in my face."
                    "I felld down and felt breaking of my head, slowly losing my life."
                    return
        "Walk around the college":
            "I left the office and started to loiter the corridor."
            "I was affected by the fact, that people, if they are here, of course, didn’t give a sign of their presence."
            th "Maybe today is a weekend?"
            th "And door wasn’t locked."
            me "On Monday?!"
            "I exclaimed indigently."
            th "Yeah, it was stupid assumption."
            th "Maybe today is some seminar?"
            th "But somebody should stayed in the dean’s office?"
            "Then I remembered, that passing by bulletin board, I hadn’t found any announcements about grand events this day."
            th "I refuse to understand this situation!"
            "I had already did a third round along the corridor, explored every door, found out  where is biology and was about to start the firth  \"round-the-corridor\" journey, when I had heard steps."
            "Somebody went Unceartanly, he stopped often, and tried not to make noise, that was unsuccessful."
            th "At least someone here is alive."
            th "But why do he walk so starnge?"
            th "Maybe he is another lost enrolee."
            th "Or a thief?"
            th "What to do? Go meet him or hide, to stay ununnoticed?"
            menu:
                "Hide":
                    "I checked every door, as luck would have it everyone was closed."
                    th "Suka blyat!"
                    "I hadn’t found a better solution, than hide behind the stairs, leading on the upper floors."
                    "I lied down and waited."
                    "Soon I understood, there was nothing to afraid of: I saw Mickey, She was stalking to dean’s office."
                    "She opened door unceartanly and slowly came in."
                    "In the same moment I heard Mickey’s scream and fighting noise."
                    "I ran to help her with no thinking and saw strange scene: Mickey lied down the floor, and some small monster kicked her, on his feet I could see a hoofs."
                    "I hit it hard, so it flew away several meters."
                    "Taking an advantage I gabbed Mickey’s hand and said:"
                    me "Run!"
                    "She woke up obediently, and we rushed away."
                    "But there was no reason to hurry. A creature, that I recognized as imp from illustration to Slavic mythology, didn’t pursue us."
                    me "Everything is alright..."
                    "I said trying to, catch my breath."
                    mky "Yeah."
                    me "Mickey, What’s going on? Where are all people?"
                    mky "We are... in psychologist’s room... The devils... from the basement... Cough!"
                    "I saw, that Mickey was very painful, shock statement was over, and such a legs can really hurt."
                    me "Lay down, have a rest."
                    mky "No... we need to go to our’s..."
                    "Obviously, Mickey holds out and can’t walk."
                    "I silently picked her up in my arms."
                    me "Show the way."
                    "Mickey was quite surprised, but she smiled gratefuly:"
                    mky "Turn right and to the end of corridor."
                    $ add_event('Спас Микки')
                    $ add_event('Микки была избита')
                    #$ saved_micky = True
                    #$ micky_was_beaten = True
                    jump physchologists_office
                "Go to steps.":
                    me "Jesus Christ! What the thief will be robbing at this time?"
                    "I went to the steps and found my step-sister Mickey, She stalked somwhere."
                    "Seems like, she didn’t noticed me, so she reacted by scream to my greeting."
                    me "Why do you scream? It’s me!"
                    mky "Alex? What are you doing here?"
                    me "I wanted to enroll, why do you ask me?"
                    "Mickey become very sad."
                    mky "You shouldn’t have come here. Now you can’t leave the building."
                    me "Why?"
                    mky "The devils let nobody get out of here."
                    me "Who? Mickey, How do you feel?"
                    mky "Okay, Why do you asking?"
                    me "I think, you have a high temperature…"
                    mky "Hey! I am alright! I understand, it is hard to believe in this, but the devils got out from the basement and thunder whole the college. Everyone is in panic and don’t understand what to do."
                    me "You mean there are other people?"
                    mky "Yeah, most of them are hiding in psychologist’s room on this floor."
                    me "Can you lead me ther?"
                    mky "Sure, you are brave boy, your presence may encourage the others."
                    "I was a little bit shy of such assessment of my moral, but I had decided to solve this problem."
                    jump physchologists_office
      
label physchologists_office:      
    if 'Спас Микки' and 'Микки была избита' in events:
        "I came into psychologist's with Mickey on my hands."
        kln "Mickey! What happened with you?!"
        "Came a voice from the corner."
        "It was redhead girl with a freckles on her face. It seemed like she was drunk."
        "I thought, this girl was a friend of Mickey, because she came to her and asked:"
        kln "Are you injured?"
        aud "Keilin! Mickey looks okay, bu she’ve got a hard time. By the way, who is this boy?"
        "Said snud girl with glasses."
        kln "Indeed, who are you?"
        "I put Mickey on the Sofa and answered:"
        me "My name is Alekasnder, but you may call me Sasha or Alex."
        aud "Well, Alex, what are you doing here?"
        me "I was going to enroll to your college, but…"
        me "By the way, are you only two here or there is some body else."
        "Snud girl started to cry…"
        aud "They… They are…"
        kln "Calm down, Audrey."
        kln "Everyone was killed, only we have survived. Somewhere here must be also Irene and Shannon, but we know nothing about their fate."
        kln "Mickey went out to discover where are they and if there are other survivors, but you understand, she is unable to do anything."
        aud "What to do? Will we just sit here awaiting our fate?"
        kln "Don’t panic, Audrey. There is a man in our ranks! He will help us. Will you help us, Alex?"
        "Indeed, it was hard to imagine those girls fighting devils."
        me "Sure. What should I do?"
        kln "You need to explore the first floor and bring us anything that can help us: weapon, food, medicine…"
        me "Got It!"
        kln "I’ll go with you!"
        me "You?"
        kln "Yes, you don’t know where to go, I can help you."
        menu:
            "Accept Keilin’s help":
                me "It makes sense. Okay, let’s go!"
                $ kln_lp +=1
                $ add_event('Кейлин с Александром')
                #$ keilin_with_alex = True
                return
            "Decline Keilin’s help":
                me "No, Keilin, you should stay with Mickey."
                return
    else:
        "We came into psychologist's room." 
        "There were two girls else. One was redhead looked alike typical Irish. Another one wore glasses and was snub."
        mky "Hi girls! Guess who I brought?"
        aud "I have no Idea."
        kln "Mickey, is he your friend?"
        mky "Yeah! His name is Alex."
        me "Nice to meet you, Girls."
        kln "I have never seen him before. Did he studied in our college?"
        me "No, I just have arrived to enroll, but you know…"
        kln "Yeah…"
        aud "Alex, it is hard to ask you, but could you help us?"
        aud "We are trapped in college building, we can’t escape, because the devils will kill us in this case. Actually, You also can’t."
        me "I can help you, but I need to know what’s going on?"
        kln "It was a massacre! The devils killed everyone they saw. Blood… Death… Except us, of course."
        me "I understand. I mean, I don’t understand, but I know what to do."
        kln "Really?"
        if 'Встретил Микки и прогнал беса' in events:
            me "Firstly, we need to arm."
            me "They are afraid of cross, but it can’t kill them, so we need defend ourselves."
        else:
            aud "What should we do?"
            me "Firstly, we need to search for some supplies."
            mky "Yeah. I went to find something useful and I met you."
            "Mickey smiled, making me shy again."
    me "So I am going out. What do we need first?"
    kln "We need some weapons, food and medicine."
    mky "I will go with you."
    "I found nothing retort."
    "Mickey knows better this college."
    return